# -*- coding: utf-8 -*-
"""risk_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129dzNxeO7ZO_MSUgi1lR2EZKk0zd3XDF
"""

"""
Risk Calculator for Student Dropout Prediction
"""

import pandas as pd
import numpy as np
import json

class RiskCalculator:
    def __init__(self, low_threshold=2.5, high_threshold=5.0):
        self.low_threshold = low_threshold
        self.high_threshold = high_threshold

    def calculate_risk_score(self, student_data):
        """
        Calculate risk score based on student features

        Parameters:
        student_data: dict with keys:
            - success_rate_sem2
            - tuition_fees_up_to_date
            - debtor
            - age_at_enrollment
            - scholarship_holder
            - displaced
        """
        risk_score = 0

        # Academic factors (weight: 3)
        if 'success_rate_sem2' in student_data:
            risk_score += (1 - student_data['success_rate_sem2']) * 3

        # Financial factors (weight: 2 each)
        if 'tuition_fees_up_to_date' in student_data:
            risk_score += (1 - student_data['tuition_fees_up_to_date']) * 2

        if 'debtor' in student_data:
            risk_score += student_data['debtor'] * 2

        # Demographic factors (weight: 1)
        if 'age_at_enrollment' in student_data:
            if student_data['age_at_enrollment'] > 25:
                risk_score += 1

        # Protective factors (negative weights)
        if 'scholarship_holder' in student_data:
            risk_score -= student_data['scholarship_holder'] * 2

        if 'displaced' in student_data:
            risk_score -= student_data['displaced'] * 0.5

        return max(0, min(10, risk_score))  # Clamp between 0 and 10

    def get_risk_level(self, risk_score):
        """Determine risk level based on thresholds"""
        if risk_score < self.low_threshold:
            return "Low"
        elif risk_score > self.high_threshold:
            return "High"
        else:
            return "Medium"

    def validate_thresholds(self, df):
        """
        Validate thresholds against actual dropout data

        Parameters:
        df: DataFrame with columns ['risk_score', 'Target']
        """
        results = []

        for level in ['Low', 'Medium', 'High']:
            if level == 'Low':
                mask = df['risk_score'] < self.low_threshold
            elif level == 'High':
                mask = df['risk_score'] > self.high_threshold
            else:
                mask = (df['risk_score'] >= self.low_threshold) & (df['risk_score'] <= self.high_threshold)

            students = mask.sum()
            dropout_rate = (df[mask]['Target'] == 'Dropout').mean() if students > 0 else 0

            results.append({
                'risk_level': level,
                'students': students,
                'percentage': students / len(df) * 100,
                'dropout_rate': dropout_rate * 100
            })

        return pd.DataFrame(results)

    def save_config(self, filename='risk_config.json'):
        """Save configuration to JSON file"""
        config = {
            'risk_thresholds': {
                'low': self.low_threshold,
                'high': self.high_threshold
            },
            'validation_date': pd.Timestamp.now().strftime('%Y-%m-%d'),
            'calculator_version': '1.0'
        }

        with open(filename, 'w') as f:
            json.dump(config, f, indent=2)

        print(f"✅ Configuration saved to {filename}")
        return config

# Example usage
if __name__ == "__main__":
    # Initialize calculator with YOUR thresholds
    calculator = RiskCalculator(low_threshold=2.5, high_threshold=5.0)

    # Test with sample student
    sample_student = {
        'success_rate_sem2': 0.65,
        'tuition_fees_up_to_date': 0,
        'debtor': 1,
        'age_at_enrollment': 22,
        'scholarship_holder': 0,
        'displaced': 0
    }

    risk_score = calculator.calculate_risk_score(sample_student)
    risk_level = calculator.get_risk_level(risk_score)

    print(f"Sample Student Risk Score: {risk_score:.2f}")
    print(f"Risk Level: {risk_level}")

    # Save configuration
    calculator.save_config('risk_config.json')